Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
