language: ruby

rvm:
 - 2.5.9
 - 2.6.7
 - 2.7.3
 - 3.0.7
 - 3.1.6
 - 3.2.5
 - 3.3.4
 - ruby-head
 - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile

sudo: false

before_install:
  - gem update --system
  - gem update bundler

script:
  - bundle exec rspec
  - bundle exec rubocop
