version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    parameters:
      ruby_version:
        type: string

    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem update --system
            gem install bundler
            bundle install
      - run:
          name: Tests
          command: bundle exec rspec
      - run:
          name: Lint
          command: bundle exec rubocop

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            name: build-<< matrix.ruby_version >>
            parameters:
              ruby_version: ["2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3"]
